import { Component, Input, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RoleTranslatePipe } from 'src/app/core/pipes/role-translate.pipe';
import { IconDirective, IconService } from '@ant-design/icons-angular';
import { 
  CheckOutline, 
  DeleteOutline, 
  CloseOutline, 
  LeftOutline, 
  RightOutline, 
  CiCircleOutline, 
  ClockCircleOutline, 
  HeartOutline,
  SearchOutline,
  BellOutline,
  UserOutline,
  InfoCircleOutline,
  StarOutline,
  EyeOutline,
  EditOutline,
  DownloadOutline,
  ToolOutline,
  CalendarOutline,
  WarningOutline,
  SyncOutline,
  PieChartOutline,
  BarChartOutline,
  FileTextOutline,
  MessageOutline,
  ArrowRightOutline,
  ArrowLeftOutline,
  PlusOutline,
  MinusOutline,
  SettingOutline,
  FilterOutline,
  TagOutline,
  DollarOutline,
  SafetyOutline,
  SaveOutline,
  ReloadOutline,
  FileOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  ExclamationCircleOutline,
  QuestionCircleOutline,
  SendOutline,
  FlagOutline,
  TrophyOutline,
  LikeOutline,
  DislikeOutline,
  SmileOutline,
  FrownOutline,
  MehOutline,
  FireOutline,
  ThunderboltOutline,
  RocketOutline,
  GiftOutline,
  CrownOutline,
  BulbOutline,
  ExperimentOutline,
  BugOutline,
  CompassOutline,
  EnvironmentOutline,
  GlobalOutline,
  HomeOutline,
  TeamOutline,
  UsergroupAddOutline,
  UsergroupDeleteOutline,
  UserAddOutline,
  UserDeleteOutline,
  UserSwitchOutline,
  LockOutline,
  UnlockOutline,
  KeyOutline,
  SafetyCertificateOutline,
  SecurityScanOutline,
  ScanOutline,
  QrcodeOutline,
  CameraOutline,
  VideoCameraOutline,
  AudioOutline,
  SoundOutline,
  MutedOutline,
  PlaySquareOutline,
  PauseCircleOutline,
  StopOutline,
  LoadingOutline,
  Loading3QuartersOutline,
  RotateLeftOutline,
  RotateRightOutline,
  RedoOutline,
  UndoOutline,
  ZoomInOutline,
  ZoomOutOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  ShrinkOutline,
  ArrowsAltOutline,
  CompressOutline,
  ExpandOutline,
  FallOutline,
  RiseOutline,
  StockOutline,
  FundOutline,
  AccountBookOutline,
  AlertOutline,
  ApiOutline,
  AppstoreOutline,
  AppstoreAddOutline,
  AuditOutline,
  BankOutline,
  BarcodeOutline,
  BarsOutline,
  BlockOutline,
  BookOutline,
  BorderOutline,
  BranchesOutline,
  BuildOutline,
  CalculatorOutline,
  CarOutline,
  CarryOutOutline,
  ClearOutline,
  CloudOutline,
  CloudDownloadOutline,
  CloudUploadOutline,
  CloudSyncOutline,
  ClusterOutline,
  CodeOutline,
  CoffeeOutline,
  CommentOutline,
  ConsoleSqlOutline,
  ContactsOutline,
  ContainerOutline,
  ControlOutline,
  CopyrightOutline,
  CreditCardOutline,
  CustomerServiceOutline,
  DashboardOutline,
  DatabaseOutline,
  DeleteColumnOutline,
  DeleteRowOutline,
  DeliveredProcedureOutline,
  DeploymentUnitOutline,
  DesktopOutline,
  DisconnectOutline,
  EllipsisOutline,
  ExceptionOutline,
  ExpandAltOutline,
  ExportOutline,
  EyeInvisibleOutline,
  FieldBinaryOutline,
  FieldNumberOutline,
  FieldStringOutline,
  FieldTimeOutline,
  FileAddOutline,
  FileDoneOutline,
  FileExcelOutline,
  FileExclamationOutline,
  FileGifOutline,
  FileImageOutline,
  FileJpgOutline,
  FileMarkdownOutline,
  FilePdfOutline,
  FilePptOutline,
  FileProtectOutline,
  FileSearchOutline,
  FileSyncOutline,
  FileUnknownOutline,
  FileWordOutline,
  FileZipOutline,
  FolderAddOutline,
  FolderOpenOutline,
  FolderViewOutline,
  ForkOutline,
  FormatPainterOutline,
  FunctionOutline,
  FundProjectionScreenOutline,
  FundViewOutline,
  FunnelPlotOutline,
  GatewayOutline,
  GroupOutline,
  HddOutline,
  HistoryOutline,
  HolderOutline,
  HourglassOutline,
  IdcardOutline,
  ImportOutline,
  InboxOutline,
  InsertRowAboveOutline,
  InsertRowBelowOutline,
  InsertRowLeftOutline,
  InsertRowRightOutline,
  InsuranceOutline,
  InteractionOutline,
  LaptopOutline,
  LayoutOutline,
  LineOutline,
  LinkOutline,
  MacCommandOutline,
  MailOutline,
  ManOutline,
  MedicineBoxOutline,
  MenuOutline,
  MergeCellsOutline,
  MergeOutline,
  MobileOutline,
  MoneyCollectOutline,
  MonitorOutline,
  MoonOutline,
  MoreOutline,
  NodeCollapseOutline,
  NodeExpandOutline,
  NodeIndexOutline,
  NotificationOutline,
  NumberOutline,
  OneToOneOutline,
  PaperClipOutline,
  PartitionOutline,
  PayCircleOutline,
  PercentageOutline,
  PhoneOutline,
  PictureOutline,
  PoundCircleOutline,
  PoundOutline,
  PoweroffOutline,
  PrinterOutline,
  ProductOutline,
  ProfileOutline,
  ProjectOutline,
  PropertySafetyOutline,
  PullRequestOutline,
  PushpinOutline,
  ReadOutline,
  ReconciliationOutline,
  RedEnvelopeOutline,
  RestOutline,
  RobotOutline,
  SubnodeOutline,
  SunOutline,
  SwitcherOutline,
  TabletOutline,
  TagsOutline,
  ToTopOutline,
  TrademarkCircleOutline,
  TrademarkOutline,
  TransactionOutline,
  TranslationOutline,
  TruckOutline,
  UngroupOutline,
  UploadOutline,
  UsbOutline,
  VerifiedOutline,
  VideoCameraAddOutline,
  WalletOutline,
  WifiOutline,
  WomanOutline
} from '@ant-design/icons-angular/icons';

export interface RequestActivity {
  type: 'SUBMISSION' | 'COMMENT' | 'VALIDATION' | 'REJECTION' | 'PAYMENT' | 'CLOSURE' | 'UPDATE' | 'REMINDER';
  status: 'pending' | 'approved' | 'rejected';
  actor: string;
  actorRole?: string;
  comment?: string;
  timestamp: string;
  details?: string;
}

@Component({
  selector: 'app-snake-timeline',
  standalone: true,
  imports: [CommonModule, RoleTranslatePipe, IconDirective],
  templateUrl: './request-activity-timeline.component.html',
  styleUrls: ['./request-activity-timeline.component.scss']
})
export class SnakeTimelineComponent implements OnInit {
  private iconService = inject(IconService);

  @Input() activities: RequestActivity[] = [];
  hoveredStep: number | null = null;

  constructor() {
    // Register all required icons
    this.iconService.addIcon(
      CheckOutline,
      DeleteOutline,
      CloseOutline,
      LeftOutline,
      RightOutline,
      CiCircleOutline,
      ClockCircleOutline,
      HeartOutline,
      SearchOutline,
      BellOutline,
      UserOutline,
      InfoCircleOutline,
      StarOutline,
      EyeOutline,
      EditOutline,
      DownloadOutline,
      ToolOutline,
      CalendarOutline,
      WarningOutline,
      SyncOutline,
      PieChartOutline,
      BarChartOutline,
      FileTextOutline,
      MessageOutline,
      ArrowRightOutline,
      ArrowLeftOutline,
      PlusOutline,
      MinusOutline,
      SettingOutline,
      FilterOutline,
      TagOutline,
      DollarOutline,
      SafetyOutline,
      SaveOutline,
      ReloadOutline,
      FileOutline,
      CheckCircleOutline,
      CloseCircleOutline,
      ExclamationCircleOutline,
      QuestionCircleOutline,
      SendOutline,
      FlagOutline,
      TrophyOutline,
      LikeOutline,
      DislikeOutline,
      SmileOutline,
      FrownOutline,
      MehOutline,
      FireOutline,
      ThunderboltOutline,
      RocketOutline,
      GiftOutline,
      CrownOutline,
      BulbOutline,
      ExperimentOutline,
      BugOutline,
      CompassOutline,
      EnvironmentOutline,
      GlobalOutline,
      HomeOutline,
      TeamOutline,
      UsergroupAddOutline,
      UsergroupDeleteOutline,
      UserAddOutline,
      UserDeleteOutline,
      UserSwitchOutline,
      LockOutline,
      UnlockOutline,
      KeyOutline,
      SafetyCertificateOutline,
      SecurityScanOutline,
      ScanOutline,
      QrcodeOutline,
      CameraOutline,
      VideoCameraOutline,
      AudioOutline,
      SoundOutline,
      MutedOutline,
      PlaySquareOutline,
      PauseCircleOutline,
      StopOutline,
      LoadingOutline,
      Loading3QuartersOutline,
      RotateLeftOutline,
      RotateRightOutline,
      RedoOutline,
      UndoOutline,
      ZoomInOutline,
      ZoomOutOutline,
      FullscreenOutline,
      FullscreenExitOutline,
      ShrinkOutline,
      ArrowsAltOutline,
      CompressOutline,
      ExpandOutline,
      FallOutline,
      RiseOutline,
      StockOutline,
      FundOutline,
      AccountBookOutline,
      AlertOutline,
      ApiOutline,
      AppstoreOutline,
      AppstoreAddOutline,
      AuditOutline,
      BankOutline,
      BarcodeOutline,
      BarsOutline,
      BlockOutline,
      BookOutline,
      BorderOutline,
      BranchesOutline,
      BuildOutline,
      CalculatorOutline,
      CarOutline,
      CarryOutOutline,
      ClearOutline,
      CloudOutline,
      CloudDownloadOutline,
      CloudUploadOutline,
      CloudSyncOutline,
      ClusterOutline,
      CodeOutline,
      CoffeeOutline,
      CommentOutline,
      ConsoleSqlOutline,
      ContactsOutline,
      ContainerOutline,
      ControlOutline,
      CopyrightOutline,
      CreditCardOutline,
      CustomerServiceOutline,
      DashboardOutline,
      DatabaseOutline,
      DeleteColumnOutline,
      DeleteRowOutline,
      DeliveredProcedureOutline,
      DeploymentUnitOutline,
      DesktopOutline,
      DisconnectOutline,
      EllipsisOutline,
      ExceptionOutline,
      ExpandAltOutline,
      ExportOutline,
      EyeInvisibleOutline,
      FieldBinaryOutline,
      FieldNumberOutline,
      FieldStringOutline,
      FieldTimeOutline,
      FileAddOutline,
      FileDoneOutline,
      FileExcelOutline,
      FileExclamationOutline,
      FileGifOutline,
      FileImageOutline,
      FileJpgOutline,
      FileMarkdownOutline,
      FilePdfOutline,
      FilePptOutline,
      FileProtectOutline,
      FileSearchOutline,
      FileSyncOutline,
      FileUnknownOutline,
      FileWordOutline,
      FileZipOutline,
      FolderAddOutline,
      FolderOpenOutline,
      FolderViewOutline,
      ForkOutline,
      FormatPainterOutline,
      FunctionOutline,
      FundProjectionScreenOutline,
      FundViewOutline,
      FunnelPlotOutline,
      GatewayOutline,
      GroupOutline,
      HddOutline,
      HistoryOutline,
      HolderOutline,
      HourglassOutline,
      IdcardOutline,
      ImportOutline,
      InboxOutline,
      InsertRowAboveOutline,
      InsertRowBelowOutline,
      InsertRowLeftOutline,
      InsertRowRightOutline,
      InsuranceOutline,
      InteractionOutline,
      LaptopOutline,
      LayoutOutline,
      LineOutline,
      LinkOutline,
      MacCommandOutline,
      MailOutline,
      ManOutline,
      MedicineBoxOutline,
      MenuOutline,
      MergeCellsOutline,
      MergeOutline,
      MobileOutline,
      MoneyCollectOutline,
      MonitorOutline,
      MoonOutline,
      MoreOutline,
      NodeCollapseOutline,
      NodeExpandOutline,
      NodeIndexOutline,
      NotificationOutline,
      NumberOutline,
      OneToOneOutline,
      PaperClipOutline,
      PartitionOutline,
      PayCircleOutline,
      PercentageOutline,
      PhoneOutline,
      PictureOutline,
      PoundCircleOutline,
      PoundOutline,
      PoweroffOutline,
      PrinterOutline,
      ProductOutline,
      ProfileOutline,
      ProjectOutline,
      PropertySafetyOutline,
      PullRequestOutline,
      PushpinOutline,
      ReadOutline,
      ReconciliationOutline,
      RedEnvelopeOutline,
      RestOutline,
      RobotOutline,
      SubnodeOutline,
      SunOutline,
      SwitcherOutline,
      TabletOutline,
      TagsOutline,
      ToTopOutline,
      TrademarkCircleOutline,
      TrademarkOutline,
      TransactionOutline,
      TranslationOutline,
      TruckOutline,
      UngroupOutline,
      UploadOutline,
      UsbOutline,
      VerifiedOutline,
      VideoCameraAddOutline,
      WalletOutline,
      WifiOutline,
      WomanOutline
    );
  }

  ngOnInit() {}

  isStepCompleted(index: number): boolean {
    return this.activities[index]?.status === 'approved';
  }

  isStepActive(index: number): boolean {
    // Optionally, highlight the last approved or first pending
    const firstPending = this.activities.findIndex(a => a.status === 'pending');
    return index === (firstPending === -1 ? this.activities.length - 1 : firstPending);
  }

  isStepPending(index: number): boolean {
    return this.activities[index]?.status === 'pending';
  }

  getCompletedStepsCount(): number {
    return this.activities.filter(a => a.status === 'approved').length;
  }

  getRemainingStepsCount(): number {
    return this.activities.length - this.getCompletedStepsCount();
  }

  getCompletionPercentage(): number {
    if (this.activities.length === 0) return 0;
    const percent = (this.getCompletedStepsCount() / this.activities.length) * 100;
    return percent > 100 ? 100 : Math.round(percent);
  }

  getIcon(type: string): string {
    const icons: { [key: string]: string } = {
      'SUBMISSION': 'send',
      'COMMENT': 'message',
      'VALIDATION': 'check-circle',
      'REJECTION': 'close-circle',
      'PAYMENT': 'dollar',
      'CLOSURE': 'flag',
      'UPDATE': 'edit',
      'REMINDER': 'bell'
    };
    return icons[type] || 'info-circle';
  }

  getActionLabel(type: string): string {
    const labels: { [key: string]: string } = {
      'SUBMISSION': 'a soumis la demande d\'avance',
      'COMMENT': 'a ajouté un commentaire',
      'VALIDATION': 'a validé la demande',
      'REJECTION': 'a rejeté la demande',
      'PAYMENT': 'a effectué le paiement',
      'CLOSURE': 'a clôturé le dossier',
      'UPDATE': 'a mis à jour la demande',
      'REMINDER': 'a envoyé un rappel'
    };
    return labels[type] || 'a effectué une action';
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'approved':
        return 'status-completed';
      case 'pending':
        return 'status-pending';
      case 'rejected':
        return 'status-rejected';
      default:
        return 'status-pending';
    }
  }

  getStatusIcon(status: string): string {
    switch (status) {
      case 'approved':
        return 'check-circle';
      case 'pending':
        return 'clock';
      case 'rejected':
        return 'close-circle';
      default:
        return 'question-circle';
    }
  }

  getStatusLabel(status: string): string {
    switch (status) {
      case 'approved':
        return 'Approuvée';
      case 'pending':
        return 'En attente';
      case 'rejected':
        return 'Rejetée';
      default:
        return status;
    }
  }
} 